#!/bin/bash
#
# Script to setup everything necessary for
# the evaluation
#
# Usage: 'sudo ./baby_setup'

url="https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz"
install_dir="/opt/maven"

apt update -y && apt install -y openjdk-17-jdk curl nginx
mkdir ${install_dir}
curl -fsSL ${url} | tar zx --strip-components=1 -C ${install_dir}
cat << EOF > /etc/profile.d/maven.sh
#!/bin/sh
export MAVEN_HOME=${install_dir}
export M2_HOME=${install_dir}
export M2=${install_dir}/bin
export PATH=${install_dir}/bin:$PATH
EOF
source /etc/profile.d/maven.sh
echo maven installed to ${install_dir}
mvn --version
bash nginx_setup
cd BabyServer || exit 1; mvn package; java -jar ./target/BabyServer-0.0.1-SNAPSHOT.jar
