#!/bin/bash
#
# Setup nginx

cat << EOF > /etc/nginx/conf.d/nginx.conf
server {
    listen 80;
    server_name localhost;

    location / {
        root $(pwd)/BabyClient;
        index index.html baby_front.html;
    }
}
EOF
rm /etc/nginx/sites-enabled/default
nginx -s reload 
